# Generated by Django 4.2.6 on 2023-10-10 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 10, 10, 14, 49, 48, 767889, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="last_edited",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="student",
            name="profile_picture",
            field=models.ImageField(
                default=datetime.datetime(
                    2023, 10, 10, 14, 49, 53, 151521, tzinfo=datetime.timezone.utc
                ),
                upload_to="profile_pictures",
            ),
            preserve_default=False,
        ),
    ]
