# Generated by Django 4.2.6 on 2023-10-16 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_student_created_student_last_edited_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="institute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.institute",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="profile_picture",
            field=models.ImageField(upload_to="static/profile_pictures"),
        ),
    ]
