# Generated by Django 4.2.6 on 2024-01-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_alter_student_institute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="password",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="teacher",
            name="password",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
