# Generated by Django 4.2.6 on 2024-01-28 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0015_question_active"),
        ("organization", "0004_student_password_teacher_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="institute",
            name="languages",
            field=models.ManyToManyField(
                related_name="languages", to="content.language"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
