# Generated by Django 4.2.6 on 2024-01-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "organization",
            "0006_teacher_created_teacher_email_teacher_last_edited_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="profile_picture",
        ),
    ]
