# Generated by Django 4.2.6 on 2024-01-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0008_alter_teacher_name_alter_teacher_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
