# Generated by Django 4.2.6 on 2024-01-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0009_student_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
