# Generated by Django 4.2.6 on 2023-10-07 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Learning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("image", models.ImageField(upload_to="learnings/")),
                ("audio", models.FileField(upload_to="audios/")),
                ("order", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Audio and Text with Multiple Choice"),
                            (2, "Image and Text with Text Answer"),
                            (3, "Matching Text and Images"),
                        ]
                    ),
                ),
                ("question_text", models.TextField(blank=True, null=True)),
                (
                    "question_image",
                    models.ImageField(blank=True, null=True, upload_to="questions/"),
                ),
                (
                    "question_audio",
                    models.FileField(blank=True, null=True, upload_to="questions/"),
                ),
                (
                    "learning",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.learning",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MultipleChoiceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="options/")),
                ("text", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="content.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matching",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="matchings/")),
                ("correct_order", models.PositiveIntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField()),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.chapter",
                    ),
                ),
            ],
            options={
                "unique_together": {("chapter", "order")},
            },
        ),
        migrations.AddField(
            model_name="learning",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="content.lesson"
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="content.language"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="learning",
            unique_together={("lesson", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together={("language", "order")},
        ),
    ]
