# Generated by Django 4.2.6 on 2023-10-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="picture",
            field=models.ImageField(null=True, upload_to="language_pictures"),
        ),
    ]
