# Generated by Django 4.2.6 on 2023-10-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_language_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="picture",
            field=models.ImageField(null=True, upload_to="static/language_pictures"),
        ),
    ]
