# Generated by Django 4.2.6 on 2023-10-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_alter_language_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name="language",
            name="native_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="language",
            name="speak_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
