# Generated by Django 4.2.6 on 2023-10-17 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_language_active_language_native_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 10, 17, 5, 47, 20, 681033, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="language",
            name="last_edited",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
