# Generated by Django 4.2.6 on 2023-11-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_language_created_language_last_edited"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="backgroundColor",
            field=models.CharField(default="bg-[#58cc02]", max_length=20),
        ),
        migrations.AddField(
            model_name="chapter",
            name="borderColor",
            field=models.CharField(default="border-[#46a302]", max_length=20),
        ),
        migrations.AddField(
            model_name="chapter",
            name="textColor",
            field=models.CharField(default="text-[#58cc02]", max_length=20),
        ),
    ]
