# Generated by Django 4.2.6 on 2023-11-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_chapter_backgroundcolor_chapter_bordercolor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="backgroundColor",
            field=models.CharField(blank=True, default="bg-[#58cc02]", max_length=20),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="borderColor",
            field=models.CharField(
                blank=True, default="border-[#46a302]", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="textColor",
            field=models.CharField(blank=True, default="text-[#58cc02]", max_length=20),
        ),
    ]
