# Generated by Django 4.2.6 on 2023-11-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_alter_chapter_backgroundcolor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="lessonType",
            field=models.CharField(
                choices=[
                    ("", "Blank"),
                    ("star", "Star"),
                    ("book", "Book"),
                    ("trophy", "Trophy"),
                    ("dumbell", "Dumbell"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
