# Generated by Django 4.2.6 on 2023-11-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_lesson_lessontype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="lessonType",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Blank"),
                    ("star", "Star"),
                    ("book", "Book"),
                    ("trophy", "Trophy"),
                    ("dumbell", "Dumbell"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
