# Generated by Django 4.2.6 on 2023-11-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_alter_lesson_lessontype"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="visibility",
            field=models.BooleanField(default=True),
        ),
    ]
