# Generated by Django 4.2.6 on 2023-11-29 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_remove_matching_question_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "questionType",
                    models.CharField(
                        choices=[
                            ("L", "L"),
                            ("P1", "P1"),
                            ("P2", "P2"),
                            ("Q", "Q"),
                            ("QP1", "QP1"),
                            ("QP2", "QP2"),
                        ],
                        max_length=10,
                    ),
                ),
                ("questionText", models.TextField(blank=True)),
                ("answerText", models.TextField(blank=True)),
                ("audioPath1", models.URLField(blank=True)),
                ("audioPath2", models.URLField(blank=True)),
                ("correctImagePath", models.URLField(blank=True)),
                ("correctImagePath2", models.URLField(blank=True)),
                ("wrongImagePath1", models.URLField(blank=True)),
                ("wrongImagePath2", models.URLField(blank=True)),
                ("wrongImagePath3", models.URLField(blank=True)),
                ("wrongImagePath4", models.URLField(blank=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="content.lesson"
                    ),
                ),
            ],
        ),
    ]
