# Generated by Django 4.2.6 on 2023-12-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_remove_question_correctimagepath_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="questionType",
            field=models.CharField(
                choices=[
                    ("L1", "L1"),
                    ("P1", "P1"),
                    ("P2", "P2"),
                    ("Q", "Q"),
                    ("QP1", "QP1"),
                    ("QP2", "QP2"),
                ],
                max_length=10,
            ),
        ),
    ]
